version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - rsa-net

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - rsa-net
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000

networks:
  rsa-net:
    driver: bridge
